### ISSUE TITLE
Hardcoded report

### ISSUE THREAD

**Issue by kana-sama** [codedownio/time-ghc-modules#3]
It just gives me the default html report for `hledger` from here - https://github.com/codedownio/time-ghc-modules/blob/fce507081f30a32c5005a781a54e226ffca7c5ba/src/index.html

**Comment by archaeron** [comment]
@kana-sama it works if you replace with `window.module_data = "INSERT_DATA_HERE";` in `src/index.html`

**Comment by thomasjm** [comment]
Sorry, I stupidly checked in my test data. Fixed now!
