### ISSUE TITLE
Total Time Unclear

### ISSUE THREAD

**Issue by m4dc4p** [codedownio/time-ghc-modules#6]
(This is a great tool - thanks so much!)

In the upper right of the generated report, I see:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/18689/128426981-95a82f39-f1c5-4b0c-b069-595b546cbda6.png">

(which says "Total time: 136.8m")

My build only took about 15 minutes (as measured by the wall clock). 

Is the total time the sum of all modules, even those done in parallel?

**Comment by thomasjm** [comment]
Exactly, it's the sum of all the "time" fields we saw in the data. If you ran your build on ~9 cores then that result sounds about right.

**Comment by m4dc4p** [comment]
Appreciate the clarification!
