### ISSUE TITLE
Add to Nixpkgs

### ISSUE THREAD

**Issue by teto** [codedownio/time-ghc-modules#7]
hi,

this is pretty awesome and this made evident some degenerate build time in a module that I already suspected. Do you plan to put this on hackage to help other ecosystems to pick it up (nixpkgs generates its haskell packages from hackage) ?

**Comment by thomasjm** [comment]
Thanks! Hmm, I don't think it's possible to put on Hackage since it's not actually a Haskell project. I think packaging it in Nixpkgs would be great though.
