### ISSUE TITLE
(MacOS) find: -printf: unknown primary or operator

### ISSUE THREAD

**Issue by nitinprakash96** [codedownio/time-ghc-modules#8]
While running it on a macos, it errors out with the error,
> find: -printf: unknown primary or operator

There's no `printf` flag in `man find` as well. Although, there's `-print` and `-print0`. In order to run it I had to remove `-printf '.'` from `NUM_PROCESSED` in `time-ghc-modules`. According to the docs,
```
 -print  This primary always evaluates to true.  It prints the pathname of the current file to standard output.
```
So I'm assuming removing it doesn't do any harm.

This might not be much of any issue as much as I'm just noting it down here if someone else stumbles upon it as well.

p.s. Thanks for this tool. It has been working great!

**Comment by thomasjm** [comment]
Hmm, sounds like a difference between GNU find and the MacOS version.

The right fix is probably to detect which `find` is being used and switch the command.

**Comment by nitinprakash96** [comment]
Sounds about right. MacOS has BSD `find`. Thanks a lot!
